# Name of the server that plugin is running on ( useful for bungeecord or other proxies use )
server: default

# Storage type ( sqlite / mysql )
storage: sqlite

# MySQL login information ( needed just if storage type is mysql)
mysql-username: your_username
mysql-password: your_password
mysql-database: your_database
mysql-host: 127.0.0.1
mysql-port: 3306

# Is reason required in report command? (example: /report Alijk <reason>)
reason-required: true

# Cooldown for report command ( in seconds ) you can use -1 to disable cooldown
cooldown: -1