#  /$$      /$$                               /$$$$$$$                                            /$$             
# | $$$    /$$$                              | $$__  $$                                          | $$             
# | $$$$  /$$$$  /$$$$$$   /$$$$$$   /$$$$$$ | $$  \ $$  /$$$$$$   /$$$$$$   /$$$$$$   /$$$$$$  /$$$$$$   /$$$$$$$
# | $$ $$/$$ $$ /$$__  $$ /$$__  $$ |____  $$| $$$$$$$/ /$$__  $$ /$$__  $$ /$$__  $$ /$$__  $$|_  $$_/  /$$_____/
# | $$  $$$| $$| $$$$$$$$| $$  \ $$  /$$$$$$$| $$__  $$| $$$$$$$$| $$  \ $$| $$  \ $$| $$  \__/  | $$   |  $$$$$$ 
# | $$\  $ | $$| $$_____/| $$  | $$ /$$__  $$| $$  \ $$| $$_____/| $$  | $$| $$  | $$| $$        | $$ /$$\____  $$
# | $$ \/  | $$|  $$$$$$$|  $$$$$$$|  $$$$$$$| $$  | $$|  $$$$$$$| $$$$$$$/|  $$$$$$/| $$        |  $$$$//$$$$$$$/
# |__/     |__/ \_______/ \____  $$ \_______/|__/  |__/ \_______/| $$____/  \______/ |__/         \___/ |_______/ 
#                         /$$  \ $$                              | $$                                             
#                        |  $$$$$$/                              | $$                                             
#                         \______/                               |__/         


# Name of the server that plugin is running on
# - Useful for cross proxy use
# - Use a VALID BungeeCord server name
server: default

# Cooldown for report command ( in seconds ) you can use -1 to disable cooldown
cooldown: -1

# Specifies that if plugin is running on BungeeCord mode ( if it is, teleporting to report system would send you to specific server )
bungeecord: false

# Options that are required to report
report-requirements:
  # Is reason required in report command? (example: /report Alijk <reason>)
  reason: true
  # Should we check if the target is online and then allow reporting?
  online-target: true
  # Should we check if the player is not reporting himself?
  prevent-self-report: true

# Commands that will be executed on player before teleporting to report location
  # Bungee commands are not supported here
  # Prefixes:
  # - [console] = Run this command from console
  # - [player] = Run this command from player
  # Placeholders:
  #    - %player% = Username of the player
teleport-enter-commands:
  - "[console] vanish %player% on"
  - "[console] gamemode spectator %player%"

# Commands that will be executed on player report exit
  # Prefixes:
  # - [console] = Run this command from console
  # - [player] = Run this command from player
  # - [server] = Send player to this server after exiting, Only works in bungee mode (Ex. [server] lobby)
  # Placeholders:
  #    - %player% = Username of the player
teleport-exit-commands:
  - "[console] vanish %player% off"
  - "[console] gamemode adventure %player%"

