# Name of the server that plugin is running on ( useful for bungeecord or other proxies use )
server: default

# Cooldown for report command ( in seconds ) you can use -1 to disable cooldown
cooldown: -1

# Storage related options
storage:
  # Storage type ( sqlite / mysql )
  type: sqlite
  # MySQL login information ( needed just if storage type is mysql)
  mysql:
    username: your_username
    password: your_password
    database: your_database
    host: 127.0.0.1
    port: 3306

# Options that are required to report
report-requirements:
  # Is reason required in report command? (example: /report Alijk <reason>)
  reason: true
  # Should we check if the target is online and then allow reporting?
  online-target: true

# Discord integration - By enabling this section you could get notified with a new message when a new report happens
# Our integration does not need any 3rd party library,plugin ...
# Just easily create a new webhook for the channel you want and paste it here, We'll do the rest
discord:
  enable: false
  webhook-url: your_webhook_url
  # You could customize title / description of embed message
  # Placeholders:
  #    - %reporter% = Username of the reporter
  #    - %target% = Username of the player that get reported
  #    - %reason% = /report user <reason> will show the reason part ( if reason is not required in config.yml may return empty space )
  embed:
    title: "%reporter% has reported %target%"
    description: "**Reason:** %reason%"
    footer: "Powered by MegaReports"
    thumbnail-url: "https://cdn.discordapp.com/attachments/889493853835497473/889502986353659944/report.png"