name: ${project.artifactId}
version: ${project.version}
main: ir.jeykey.megareports.MegaReports
authors: [ Alijk ]
description: ${project.description}
website: ${project.url}
commands:
  report:
    description: Report a player
    usage: /<command>
  megareports:
    description: MegaReports plugin main command
    usage: /<command>
  reports:
    description: Managing reports
    usage: /<command>
